### ISSUE TITLE
python error?

### ISSUE THREAD

**Issue by ThelVlilkman** [Just-Some-Bots/ModTools#39]
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 932, in _extract_signature_function
    cache_res = res(test_string)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 984, in <lambda>
    return lambda s: initial_function([s])
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: 'qC'
 (caused by KeyError('qC',))

**Comment by loveens** [comment]
I have this issue as well, is there any way to fix it? I installed a new version of youtube-dl and restarted the bot, but it didn't help. It play _some_ YT songs, but it gives the error in most cases.

**Comment by ImthePeach** [comment]
Reference [#806](https://github.com/Just-Some-Bots/MusicBot/issues/806)
This also isn't even the right repository, you were looking for the musicbot, not mod tools.
