### ISSUE TITLE
The bot won't play anything.

### ISSUE THREAD

**Issue by EightBitBoot** [Just-Some-Bots/ModTools#40]
This has occurred across two machines one Linux, one Windows.

Youtube Error:

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Adin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 997, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Adin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 924, in _extract_signature_function
    cache_res = res(test_string)
  File "C:\Users\Adin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 976, in <lambda>
    return lambda s: initial_function([s])
  File "C:\Users\Adin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "C:\Users\Adin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "C:\Users\Adin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: 'Ai'
 (caused by KeyError('Ai',))
<class 'musicbot.exceptions.CommandError'>: ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Adin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 997, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Adin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 924, in _extract_signature_function
    cache_res = res(test_string)
  File "C:\Users\Adin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 976, in <lambda>
    return lambda s: initial_function([s])
  File "C:\Users\Adin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "C:\Users\Adin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "C:\Users\Adin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: 'Ai'
 (caused by KeyError('Ai',))

Soundcloud Error:

ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>)
<class 'musicbot.exceptions.CommandError'>: ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>)

**Comment by EightBitBoot** [comment]
Sorry wrong repo.  My bad.
